name: Cache

on:
  workflow_dispatch:

jobs:
  run_smoke_tests:
    runs-on: ubuntu-20.04
    permissions:
      contents: write

    defaults:
      run:
        shell: bash

    steps:
    - uses: actions/checkout@v1

    - uses: actions/setup-python@v2

    - uses: syphar/restore-virtualenv@v1
      id: cache-virtualenv
      with:
        requirement_files: requirements.txt  # this is optional

    - uses: syphar/restore-pip-download-cache@v1
      if: steps.cache-virtualenv.outputs.cache-hit != 'true'

      # the package installation will only be executed when the
      # requirements-files have changed.
    - run: pip install -r requirements.txt
      if: steps.cache-virtualenv.outputs.cache-hit != 'true'

    # - name: Test
    #   run: behave login.feature

      # - name: Install Python 3
      #   uses: actions/setup-python@v1
      #   with:
      #     python-version: 3.9

      # - name: Cache virtual environment
      #   id: cache-venv
      #   uses: actions/cache@v2
      #   with:
      #     path: .venv/
      #     key: ${{ runner.os }}-venv-${{ hashFiles('./qa_requirements.txt') }}
      #     restore-keys: |
      #       ${{ runner.os }}-venv-

      # - name: Install dependencies
      #   run: python -m venv .venv && ./.venv/bin/activate && pip install --upgrade pip && pip install -r qa_requirements.txt
      #   if: steps.cache-venv.outputs.cache-hit != 'true'

      # - name: Run tests with behave 1
      #   run: |
      #     ./.venv/bin/activate &&
          # behave login.feature -f allure_behave.formatter:AllureFormatter -o ../allure-results1 --no-capture