name: Run Smoke Tests Parallel

on:
  workflow_dispatch:
    inputs:
      tags:
        description: "Test scenario tags"
        required: true
        default: "smoke"

jobs:
  run_smoke_tests:
    runs-on: ubuntu-20.04
    permissions:
      contents: write

    strategy:
      matrix:
        test-suites: ['login', 'login_normal']

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Install Python 3
        uses: actions/setup-python@v1
        with:
          python-version: 3.9

      - name: Install dependencies
        run: python -m venv venv && ./venv/bin/activate && pip install --upgrade pip && pip install -r qa_requirements.txt
        if: steps.cache-venv.outputs.cache-hit != 'true'

      - name: Run tests with behave ${{ matrix.test-suites}}
        run: |
          ./venv/bin/activate &&
          behave tests/${{ matrix.test-suites}}.feature -f allure_behave.formatter:AllureFormatter -o allure_result_${{ matrix.test-suites}} --no-capture

      - name: Prepare Allure history
        run: |
          mkdir -p allure-results
          mv allure_result_${{ matrix.test-suites}}/* allure-results
          ls allure-results

      - name: Upload Allure results artifact
        uses: actions/upload-artifact@v3
        with:
          name: allure-results-art
          path: allure-results

  serve_allure_report:
    needs: run_smoke_tests
    runs-on: ubuntu-20.04
    permissions:
      contents: write

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Download Allure results artifact
        uses: actions/download-artifact@v3
        with:
          name: allure-results-art
          path: allure-results

      - name: Get Allure history
        uses: actions/checkout@v2
        if: always()
        continue-on-error: true
        with:
          ref: gh-pages
          path: gh-pages

      - name: Allure report action
        uses: simple-elf/allure-report-action@master
        if: always()
        with:
          allure_results: allure-results
          allure_history: allure-history
          # keep_reports: 5

      - name: Deploy Allure report to GitHub Pages
        id: gh-pages
        if: always()
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.ACTIONS_TOKEN }}
          publish_branch: gh-pages
          publish_dir: allure-history



